### ISSUE TITLE
Feature improvements

### ISSUE THREAD

**Issue by Niek** [luminati-io/luminati-proxy#1]
I'm testing this and it works pretty well, just a few ideas of what could be improved:
* Ability to spawn multiple ports, each in different zone/country/etc.
  * Right now, I need to spawn multiple processes to achieve this
  * Suggestion for syntax: ``-p 1234 --country de -p 1235 --country us``
* Allow runtime country/session change, similar to (same as?) http://trigger.domain/hola_trigger/options
  * Only way to achieve this now is to stop the process and restart it
* Logging of requested URLs + filesize to log file or stdout
  * Suggested format: ``[12345 bytes] http://url/requested``
* Documentation, specifically:
  * SSL: what's needed for the self-signed cert?
  * Include/exclude patterns: is this a comma separated list of patterns? How to specify wildcards? Etc.

**Comment by giladno** [comment]
- You can already spawn multiple configuration etc. Instead of passing the arguments in the command line, you can put them into a json file and pass the filename as an argument
- We are working on adding an API to dynamically create proxies at runtime
- All requests/responses will be logged into sqlite database and we'll add a UI to view them
- SSL: you can either disable ssl checks with your client (such as "-k" flag with cURL) or install the CA as trusted (http://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list)
- Include/Exclude patterns are treated as regular expressions

**Comment by Niek** [comment]
Thanks for the reply!
* Do you have a sample JSON config? Do the keys map 1:1 to the parameters? How to specify the JSON config (I can't find the option for it)?
* Dynamic proxy: can you at least allow the hola_trigger requests as a workaround?
* Where is the sqllite file stored? Any chance the file/location can be specified with a parameter?
* SSL: any example how to generate the SSL cert?
* Example for the include/exclude patterns?

**Comment by giladno** [comment]
- Keys map 1-1 to the parameters. So you can have a file "us.json" with:
```
{"country": "us"}
```
and a file "uk.json":
```
{"country":"uk"}
```
and then you can start it with:
```
$ luminati us.json uk.json
```

Dynamic requests: it will be available soon
Sqlite: it is stored in your home folder, but you won't need to access it directly, we'll provide a UI to access the data
SSL: we already provided a self-signed certificate as part of the package, we will expose it via the UI so you can access it easily
Exclude example for images:   "\.(png|gif|jpg)$"

**Comment by lee-elenbaas** [comment]
one note about the configuration files - they can each be a single proxy object, or an array that contain multiple proxy definitions

**Comment by Niek** [comment]
Just for reference:

Points 1 and 2 are resolved with the /api/create call, sample: **POST** /api/create ``country=de&port=23001&session=1234``

The logging issue is still open, it would be great if all calls could be logged to a text file.

**Comment by lee-elenbaas** [comment]
right now if you use the --history command line option - you will have all the requests logged into the sqlight3 file - currently that file can be viewed using other sqlight view tools - but we are working on adding UI for that

**Comment by Niek** [comment]
I would recommend to make it possible to provide a filename to --history so at least the location of the sqlight3 file can be specified.

**Comment by lee-elenbaas** [comment]
good idea

**Comment by Niek** [comment]
I just tested, --history is not working. The file (``$HOME/.luminati.sqlite3``) is created, nothing is stored in both the ``request`` and ``ip`` tables.

**Comment by lee-elenbaas** [comment]
--history has been working for us for a while - what parameters have you used? what requests have you done while runing it?

**Comment by lee-elenbaas** [comment]
@Niek without more info - i am closing this issue - reopen if you have some info
