### ISSUE TITLE
Luminati leaking IP to Google

### ISSUE THREAD

**Issue by billedwards1890** [luminati-io/luminati-proxy#101]
Our real IP is somehow being leaked to Google when scraping search result pages through Luminati's proxy service.

We know that our IP is being leaked because Google's captcha page includes the user's IP in its HTML (see attached screenshot)
![screenshot from 2018-05-31 14-53-41](https://user-images.githubusercontent.com/22359163/40810691-7b61a4ec-64e3-11e8-9c28-8d583d0fcffc.png)

Steps to reproduce:
1) Start Luminati via command line: luminati --no-dropin --www=<insert port> configs.json
    (configs.json contains the following settings: {"_defaults":{"customer":"your_username","password":"your_password"},"proxies":[{  "port":"<insert port>", "max_requests":3,"country":"us","keep_alive":10,"sticky_ip":false,"zone":"static"}]})
2) Configure browser to route all requests through proxy
3) Double check proxy is active by visiting http://www.showip.com
4) Continue navigating to 'https://www.google.com/search?q=test" until Google triggers captcha

What could be causing this?

The proxy service seems to be configured correctly since the IP is changing when we visit a site like showip.com.

**Comment by smatei** [comment]
I have opened a port in LPM:

`		{
		  "allow_proxy_auth": true,
		  "country": "us",
		  "ip": "216.74.76.206",
		  "port": 25001,
		  "zone": "googletest"
		}`

and choose a data center IP from my list. Setup Firefox to use my LPM:

![lpm-settings-firefox](https://user-images.githubusercontent.com/17740806/41396287-17447f62-6fb9-11e8-9e95-2e253adecf6c.jpg)

If I check the ip with lumtest.com or whatismyip.com, the result is the right data center IP:

![lpm-settings-firefox-lumtest](https://user-images.githubusercontent.com/17740806/41396340-49b14f34-6fb9-11e8-994e-cb3be720e380.jpg)

![lpm-settings-firefox-whatismyip](https://user-images.githubusercontent.com/17740806/41396346-4da74170-6fb9-11e8-8d4e-3fd7bf2b5b87.jpg)

If I ask Google "what is my ip address", the result is my LPM server IP:

![lpm-settings-firefox-google](https://user-images.githubusercontent.com/17740806/41396369-6287a30a-6fb9-11e8-85ef-f1d8dc3dd382.jpg)

I was told that the "googletest" zone has access to Google, but it looks like it does not.

**Comment by assafza** [comment]
Hello,

It is possible that some zone configuration is lacking.
Please contact your account manager for further help with the matter as we have new solutions and features for google domains.
You can contact your account manager through our control panel: http://luminati.io/cp

Thanks
