### ISSUE TITLE
Error at installation: installation script detects wrong versions of npm and node

### ISSUE THREAD

**Issue by aburkov** [luminati-io/luminati-proxy#102]
I have:

$ npm --version
5.6.0
$ node --version
v8.11.2

When I run 

> sudo npm install -g @luminati-io/luminati-proxy

i get:

> WARN engine @luminati-io/luminati-proxy@1.98.91: wanted: {"node":">=7.5","npm":"4.6.1"} (current: {"node":"4.2.6","npm":"3.5.2"})

How can I make the installation script use the true versions of npm and node?

**Comment by aburkov** [comment]
Solution: curl -L https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh | bash

**Comment by assafza** [comment]
Please use our installation script options:
wget -qO- https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh | bash
Or,
curl -L https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh | bash
