### ISSUE TITLE
Critical: luminati-proxy@1.100.731 update breaks Docker setup

### ISSUE THREAD

**Issue by sp0ng3w0rthy** [luminati-io/luminati-proxy#106]
Hey there,

Ever since the update to `@luminati-io/luminati-proxy` to version `1.100.731`, the Docker run command written in the README doesn't work anymore, instead of showing a login screen to the Luminati Proxy Manager, this error shows up:

![capture](https://user-images.githubusercontent.com/10582405/42118442-c2338c3e-7c0b-11e8-9311-b1493e061cbe.PNG)

Furthermore, I've used the `npm install -g @luminati-io/luminati-proxy` installation as well and on my local Windows machine, and after running the `luminati` executable I accessed the same local URL and it worked as expected, so this issue is only relevant to the Docker setup.

I've just tested by creating my own dockerfile that uses `@luminati-io/luminati-proxy@1.100.623` and it worked, no _Forbidden IP_ issue, therefore it is safe to assume that this issue started from version **`1.100.731`**.

**Comment by assafza** [comment]
Hi,

We have made some security updates to help your LPM process more secure. please follow the FAQ topic:
https://luminati.io/faq#proxy-security

**Comment by pea** [comment]
The docs don't explain how to add whitelist IPs while using Docker though.

I've tried every combination of this but it's still locking me out.

`CMD [ "luminati", "--www_whitelist_ips", "['185.53.225.100]" ]`
