### ISSUE TITLE
Luminati failed to install from npm

### ISSUE THREAD

**Issue by tom445** [luminati-io/luminati-proxy#108]
I am using macbook air, getting this error when trying to install luminati proxy manager from terminal

**Comment by fudali** [comment]
How do you try to install it exactly? Can you provide with the command you use?

**Comment by assafza** [comment]
Hi, please use the install script in your terminal and report back if this solves your issue: https://github.com/luminati-io/luminati-proxy#linuxmacos---install-script

If this doesn't work please contact Luminati support at http://luminati.io/cp
