### ISSUE TITLE
Unclear how to whitelist IPs while using Docker

### ISSUE THREAD

**Issue by pea** [luminati-io/luminati-proxy#109]
I've tried a combination but nothing seems to work.

In Dockerfile
```
CMD [ "luminati", "--www_whitelist_ips", "['185.53.225.100']" ]
CMD [ "luminati --www_whitelist_ips [\"185.53.225.100]\"" ]
```

In docker-compose.yaml
```
 environment:
      - www_whitelist_ips=["185.53.225.100"]
```

In .luminati.json
```
{
  "_defaults": {
    "customer": "hl_d57fa6cd",
    "logs": true,
    "password": "ynxgl4cdnm4k",
    "token": "",
    "www_whitelist_ips": ["185.53.225.100"]
  },
```
In the admin of a locally run Luminati

**Comment by pea** [comment]
I tried absolutely everything but finally the only thing that worked was downgrading to a version without IP whitelisting - v1.92.822

**Comment by JannikZed** [comment]
Hi there, for me it worked with the .luminati.json 
```
{
  "_defaults": {
    "customer": "XXXX",
    "password": "XXXXX",
    "token": "",
    "www_whitelist_ips": ["10.42.0.0"]
  },
  "proxies": [
```

The proxy shows you an error message, when you try to open the frontend with a non-whitelisted IP. I just entered this one and it worked for me in a kubernetes environment. Maybe also try to enter the IP like a whole subnet `185.53.0.0`  -> because that worked for me.. it's anyhow a really bad feature and also bad documented ..

**Comment by assafza** [comment]
You can set the www whitelist in the docker start command by doing a command
like this:

docker run luminati/luminati-proxy luminati --www_whitelist_ips 172.16.0.0/12

If you are still experiencing problems please contact luminati support.

**Comment by yanshiyason** [comment]
Hi, I am also having a problem with docker. I am trying to run the proxy manager in 1 container, and my program in another containers. 

Both containers are on the `app_default` docker network, UI is available on port `22999` and proxy is on port `24000`.

I am whitelisting ip access as `0.0.0.0/0`  which I assume allows all traffic

![image](https://user-images.githubusercontent.com/11358371/45004715-e9f38b00-b029-11e8-93ea-d6bd64ee9015.png)

I can ping the web UI from the other container (which I also allowed access form anywhere)

![image](https://user-images.githubusercontent.com/11358371/45004753-317a1700-b02a-11e8-99d9-85909003db86.png)

But I receive a 403 forbidden when trying to use the proxy:

```elixir
:httpc.set_options([proxy: {{'luminati_proxy', 24000}, []}])

**Comment by pea** [comment]
For anyone coming to this:

CMD [ "luminati", "--www_whitelist_ips", "123.123.123.123/12" ]
