### ISSUE TITLE
proxy manager hangs / slow response / high cpu

### ISSUE THREAD

**Issue by messiahUA** [luminati-io/luminati-proxy#112]
luminati-proxy version: 1.104.508

node process consumes up to 70% cpu constantly and periodically stops responding with "504 Gateway Time-out" or responds with a huge delay (may take up to 2 minutes), testing using: curl --proxy localhost:24000 http://lumtest.com/myip.json

Web UI on 9090 port doesn't load as well. Also, I've noticed that the problem is accompanied by increased cpu system time.

**Comment by jotajunior** [comment]
Are you using Long Single IP Sessions? How many concurrent sessions on average?

I'm running through a similar problem under there conditions, and I'm still considering whether to use LPM for that.

**Comment by assafza** [comment]
Hi we have added a lot of improvements regarding this issue in the latest versions. please make sure you are using the latest version. if the problem persists please contact Luminati support.
