### ISSUE TITLE
Error: SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by billedwards1890** [luminati-io/luminati-proxy#114]
Hi there,

When starting up a manager, I get the following error:
2018-08-20 21:11:05.273 ERR: 23030 start error Error: SQLITE_BUSY: database is locked
2018-08-20 21:12:19.767 ERR: Shutdown, reason is SIGTERM: undefined

After multiple retries, the error message eventually subsides, but it happens persistently on every startup.  Do you know what could be causing this?

Thanks!

**Comment by ByronAP** [comment]
happened to me also

**Comment by assafza** [comment]
hi @ByronAP @billedwards1890  please upgrade to latest version which should contain fixes on thsi issue. if the problem persists please contact our 24/7 support
