### ISSUE TITLE
How many concurrent sessions/requests LPM can handle?

### ISSUE THREAD

**Issue by jotajunior** [luminati-io/luminati-proxy#115]
Hello,

Sorry for this issue, which is much more a doubt than anything.

I'm thinking about deploying an LPM server which will serve as proxy for many other machines running session tasks.

Think about around 5k users with long lived IP sessions with 45 secs keep-alive settings, using a single LPM docker instance to proxy requests. As I imagine, the LPM container will be responsible for sending 5k keep-alive requests every 45 seconds, which is not a light task, and also proxy their requests (which will be in the order of hundreds, though not for all 5k users at the same time).

Will LPM handle it? Is it reasonable to think this might work with a good enough machine? Or will I need to develop my own keep-alive solution?

**Comment by assafza** [comment]
Hi @jotajunior, I think that the best practice would be to test and split it into few lpm instances if you see any issues arising.

**Comment by sergshyn** [comment]
Hi, it looks like I have the same situation. 

My deployment assume quite a lot requests to single LPM instance. 
In logs I see many errors "Connection refused (Connection refused)".
As I understand LMP can not handle that number of connections?

@assafza should I launch additional LPM to share load?
@jotajunior could you please share what you will do finally?
