### ISSUE TITLE
Whitelist any ip in luminati-proxy

### ISSUE THREAD

**Issue by wiliam-paradox** [luminati-io/luminati-proxy#118]
It's possible to whitelist any IP in luminati-proxy?

**Comment by assafza** [comment]
Yes you should be able to white list any wanted IP : https://luminati.io/faq#lpm_whitelist_admin

**Comment by wiliam-paradox** [comment]
> Yes you should be able to white list any wanted IP : https://luminati.io/faq#lpm_whitelist_admin

@assafza I mean, open all ips like the keyword "ANY" in luminati zone editor. I tried first time 0.0.0.0/0 but it didn't work, I will try again.

Thanks.
