### ISSUE TITLE
Feature request:1 click change proxy.

### ISSUE THREAD

**Issue by yuxden** [luminati-io/luminati-proxy#12]
Hi,

The new version is very good to create socks5 via web panel.

I have one suggestion:

Can you add a button to change socks in web panel.

And one more question:

How direct-router work?I saw some request are using direct Router in Debug model.

How can I make all request only use socks5?

Thank you@

**Comment by lee-elenbaas** [comment]
You can change the SOCKs port from the proxy settings dialog
Our socks interface is there to provide a socks interface for the luminati http proxy
so any socks request that is not http/https is routed directly - and any http/https requests goes through luminati

**Comment by yuxden** [comment]
Hi：

Change socks port will need more action.

And for Router Direct.

I use a our link such as :http://47.88.139.151/ip/ip.php?group=checkip

Then they show work in Direct router.

Can I make all request using proxy?

Thank you!

**Comment by lee-elenbaas** [comment]
requests for IP and not domain are always direct requests - that means they will go from the super proxy server and not from the proxy node
this is usually not what you want.
the luminati-proxy enable using the direct_include/exclude configuration to specify what urls should behave as direct requests
in addition to those that the service force you to (like IP urls)

what more action you need to change the SOCKs port?

**Comment by yuxden** [comment]
I see,because sometime we can't control what other website show,if we can make all request use proxy node,maybe best.

For change socks,Now we need to change the socks port and then change in our PC.

If there is a button change socks,We only need to click it.

**Comment by lee-elenbaas** [comment]
can you explain to me what it is you try to do? perhaps i'll be able to help

**Comment by yuxden** [comment]
Hi:

For Direct Router,we make a crawel for our customer,so we need to make all request with proxy.

And For 1 click change socks,our crawel server work with PC software.

**Comment by lee-elenbaas** [comment]
I am still not sure i understand - so i will try to rephrase - and you tell me if i got it correctly

You are creating a crawler - that with one click you need to be able to configure it to work with proxy and without proxy?

If that is the case - they i suggest you will implement that one click by implementing a redirection proxy yourself - and then you can configure your redirection proxy where to redirect the request

we might implement something like this in the future but not right now (you are free to do it based on this project, and we will gladly accept a pull request that enhance the luminati-proxy capabilities

**Comment by lee-elenbaas** [comment]
closed due to inactivity
