### ISSUE TITLE
HOW TO SET SOCKS5 by Use Proxy Manager

### ISSUE THREAD

**Issue by 88pan** [luminati-io/luminati-proxy#120]
Hellow,i want to Use Proxy Managerand set password for my proxy,but how to do it?Default username and password is null but i wantto change it.

**Comment by assafza** [comment]
You Proxy manager's ports are controlled by your Luminati Zones which defines the ports network type and other permissions.

If you wish to change the Zone's password you should go to your zones dashboard: http://luminati.io/cp/zones then go to the zones settings -> there you will find how to change your password. Image: https://prnt.sc/kye7n8

If you need to update the new zone password inside the Proxy manager you should Edit the port and go to General there you will see the form field to change the password. Image:  https://prnt.sc/kye83k
