### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by residualmind** [luminati-io/luminati-proxy#125]
LPM v1.108.119, docker image

I just switched on a rule with the `refresh IP` action.
There is one other rule with the trigger `status code` and the action `retry with different port`

Now 100% of requests do this:

`2018-09-28 10:56:28.683 WARN: 24000 complete req GET /dp/B078HPMPJT Cannot read property 'includes' of undefined`

**Comment by residualmind** [comment]
Update:
The error starts occurring whenever I restart LPM when I have a `refresh` rule set.

So when I set the rule, everything works, but after a restart, all requests fail with the above error.

**Comment by Stiveknx** [comment]
Same here, same case, after any restart of LPM (in my case was after server reboot)

**Comment by fudali** [comment]
Fixed
