### ISSUE TITLE
swagger.json Action is banip, not ban_ip

### ISSUE THREAD

**Issue by Stiveknx** [luminati-io/luminati-proxy#128]
https://github.com/luminati-io/luminati-proxy/blob/9119c55ca6a1cb224411c241b64c4cd816d63b77/lib/manager.js#L2474

In swagger.json the action is described by:
/proxies/{port}/ban_ip

But instead is:
/proxies/{port}/banip

**Comment by fudali** [comment]
thanks! It's gonna be fixed in the next release
