### ISSUE TITLE
Error ECONNRESET

### ISSUE THREAD

**Issue by Stiveknx** [luminati-io/luminati-proxy#129]
Getting a bunch of those ...

0|luminati_proxy_manager  | 2018-09-29 03:24:33.056 ERR: 24074 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":40667}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.056 ERR: 24029 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":35037}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.056 ERR: 24080 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":40591}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.056 ERR: 24107 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":39975}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.056 ERR: 24058 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":39529}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.056 ERR: 24065 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":41429}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.056 ERR: 24119 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":40669}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.056 ERR: 24085 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":34767}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24099 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":35449}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24093 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":43793}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24096 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":36671}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24108 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":38405}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24080 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":40591}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24089 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":34951}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24082 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":45183}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24021 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":45545}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24053 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":33957}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24020 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":36005}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.057 ERR: 24067 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":41433}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.058 ERR: 24063 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":38771}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.058 ERR: 24111 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":36921}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.058 ERR: 24107 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":39975}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.058 ERR: 24032 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":46479}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.058 ERR: 24050 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":34825}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.058 ERR: 24105 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":40405}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.058 ERR: 24092 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":46435}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.058 ERR: 24063 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":38771}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24093 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":43793}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24053 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":33957}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24107 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":39975}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24100 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":43529}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24023 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":36405}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24044 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":36427}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24024 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":42141}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24105 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":40405}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24031 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":35821}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24036 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":41565}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24044 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":36427}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24107 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":39975}
0|luminati_proxy_manager  | 2018-09-29 03:24:33.059 ERR: 24040 Socket error: {"error":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)","port":41083}

**Comment by fudali** [comment]
Hi. If this is still happening, please share with us your config file **(remember to erase the credentials)** and I'll try to reproduce the issue on our side. Once reproduced it will be fixed quickly
