### ISSUE TITLE
Feature Request: daemon mode

### ISSUE THREAD

**Issue by JohnBruce** [luminati-io/luminati-proxy#13]
It would be cool if this had a daemon mode.  When I think about it, I want this pretty always running once I start it, as constantly starting/stopping it involves a bit of connection overhead.  I guess for now I can nohup the luminati command or use a daemonizing app.  I'll also happily accept you telling me to do that as a solution.

**Comment by lee-elenbaas** [comment]
You are able to run our app using [pm2](http://pm2.keymetrics.io/)
this gives the feature you want

note that if you use pm2 to run multiple instances, make sure proxy configuration does not conflicts over ports, and that you run all your instances with the --no_dropin option to avoid conflicting on port 22225

**Comment by lee-elenbaas** [comment]
New versions already support deamon mode using -d or --deamon argument

**Comment by JohnBruce** [comment]
awesome thanks for the info
