### ISSUE TITLE
Proxy Server refuses connection

### ISSUE THREAD

**Issue by EmpireOneDevs** [luminati-io/luminati-proxy#134]
We use the Luminati Proxy Manager for HTTP proxies, a few day ago we had to change the VPS location to another provider, as documentation provided describes , we just have to download the json file and to replace  the new installation's .luminati.json file.
Installed on ubuntu 16.04 x64 machine, with no additional settings , just like the installation tutorial shows : 

 1. curl -L https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh | bash
 2. Replace the .luminati.json
 3. cli command : luminati

When trying to connect to x.x.x.x:24001 , the proxy server refuses the connection.

No firewalls, No restrictions on the machine.

By the way the installation process outputs this: 

![image](https://user-images.githubusercontent.com/40423351/47293494-f7cd9180-d612-11e8-86ce-ba23301d8b04.png)

P.S. : - 4 days nobody offering support from you guys....not serious.
Thank you

**Comment by janober** [comment]
Also have problems with the proxy. Similar to yours. Did you try to log into the UI? Because for me it only starts to work after loggin in, even when I supply user & password via config-file or CLI parameters.

**Comment by EmpireOneDevs** [comment]
> 
> 
> Also have problems with the proxy. Similar to yours. Did you try to log into the UI? Because for me it only starts to work after loggin in, even when I supply user & password via config-file or CLI parameters.

I'm not sure that i got your problem,in fact there is a bug related to the last 2 releases which relates to whitelisting ip's allowed to connect to/through LPM so actually there are 2 ways of solving this issue: 

  1. Downgrade the LPM to previous versions (2 releases behind);
    2. Whitelist all the ip's that you need to connect with through LPM in the .luminati.json config file (instead of 1.1.1.1/1)

**Comment by ntzm** [comment]
I'm also experiencing this issue after the latest releases

**Comment by fudali** [comment]
I'm sorry it took a bit time. But the issue is fixed. Just need to upgrade
