### ISSUE TITLE
Versions starting with 0.6.1 require phantomjs-prebuilt, which is not available for arm

### ISSUE THREAD

**Issue by sdossick** [luminati-io/luminati-proxy#14]
We were successfully using luminati-proxy 0.5.x on raspberry pi devices up until this change.  It looks like your only use of phantomjs is for webshot screen captures, so perhaps you could make phantomjs an optionalDependency in the package.json and then check for presence at runtime?

**Comment by lee-elenbaas** [comment]
We will look into making it optional

**Comment by danylo-hola** [comment]
This is now resolved in the way suggested.

**Comment by lee-elenbaas** [comment]
from version 0.7.1
