### ISSUE TITLE
docker image does not build

### ISSUE THREAD

**Issue by residualmind** [luminati-io/luminati-proxy#147]
As of writing this, there has not been a working docker image for the last versions of LPM since for 10 days.. That means, even if some bugs have been fixed, many people won't be able to upgrade.

https://hub.docker.com/r/luminati/luminati-proxy/builds/

**Comment by residualmind** [comment]
this might help:
https://github.com/cloudfoundry-incubator/stratos/pull/2252/files

**Comment by fudali** [comment]
fixed
