### ISSUE TITLE
"Bad Port"  error on trying to send a HTTP request to a server that use high ports

### ISSUE THREAD

**Issue by Urahara** [luminati-io/luminati-proxy#148]
Hi,

I'm Luminati consumer, and when a trying to send a request to a url: http://example.com:10080/test i receive "Bad Port" but the server that i want send request is hosted on this port.

**Comment by mizhgun** [comment]
Hi @Urahara have you solved that? I have the same issue.

**Comment by Urahara** [comment]
@mizhgun You have to send them a email asking for the release of the port you want to use:
https://luminati.io/faq#integration-ports
