### ISSUE TITLE
Start from json config file

### ISSUE THREAD

**Issue by CatsPlugins** [luminati-io/luminati-proxy#149]
Hello,

I'm new to Luminati, currently, I'm testing on Google Chrome and Windows, everything is running OK.

But, I'm wondering what's the precise step to run it on Centos 7?

Here's my assume:

- Install: wget -qO- https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh | bash
- Start as deamon: luminati --deamon --config /file-to-json-file-that-exported-from-windows.json

So, everything will work, right?

I'm sorry for my noob question but still, I hope to get the corrects from you guys.

Thank you!

**Comment by fudali** [comment]
Hi! Yes exactly. You can also skip `--config` flag and it will the default location which is `~/luminati_proxy_manager/.luminati.json`
