### ISSUE TITLE
Unable to run parallel proxy manager processes on one machine

### ISSUE THREAD

**Issue by billedwards1890** [luminati-io/luminati-proxy#15]
The documentation currently states: "It is important to note that multiple instances of Luminati proxy manager can run on the same machine, but only if they are configured not to have conflicting ports."

How do I configure the proxy manager processes to not have conflicting ports?

I've tried running two instances of luminati with the following config files:

config1.json: {"port": "24000","country": "us","sticky_ip": true, "max_requests": 0}
config2.json: {"port": "24001","country": "us","sticky_ip": true, "max_requests": 0}

luminati --www=23000 --proxy_port=22225 config1.json
luminati --www=23001 --proxy_port=22226 config2.json

I get the following error message: "Error: listen EADDRINUSE 0.0.0.0:22225".

My end goal is to be able to cycle the IP on a specific port, while maintaining the same IP on other ports.  My understanding is that the only way to cycle IP's is to restart the process, in which case I need to be able to have different proxy manager processes running in order to maintain a persistent IP.

**Comment by lee-elenbaas** [comment]
You should also disable the drop-in proxy since it is configured to always run on port 22225
change your commands to be:

luminati --no_dropin --www=23000 --proxy_port=22225 config1.json
luminati --no_dropin --www=23001 --proxy_port=22226 config2.json
