### ISSUE TITLE
Need API support for HAR capture

### ISSUE THREAD

**Issue by dboresjo** [luminati-io/luminati-proxy#150]
Could we have API support for enabling/disabling and downloading HAR file capture please. Needs to be on a per-port basis to enable the flow (1) setup proxy on port, (2) route some traffic through it, (3) download HAR, (4) teardown port.

**Comment by fudali** [comment]
Hi! Thanks for reaching out

When you run LPM is does already expose its API on localhost. The documentation can be found here:
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/luminati-io/luminati-proxy/master/lib/swagger.json#/Proxy

You can add, edit, remote proxy ports and also download HAR logs using `GET` `/api/logs_har`

We are not planning to add support for managing logs per port through API
