### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by rikimasorati** [luminati-io/luminati-proxy#153]
I am getting this 502 error when trying to connect to my whitelisted domains (using VIP mode)
The proxy manager runs on an external ubuntu server. When I access not whitelisted domains it works, but then it does only use superproxy. 
I installed the CA in Firefox (where this happens) and also on server itself (not sure if this is necessary).

**Comment by fudali** [comment]
What do you mean by whitelisted domains? In LPM you can whitelist specific IPs or ranges for UI access or traffic access.
