### ISSUE TITLE
TypeError: Cannot read property 'tooltip' of undefined

### ISSUE THREAD

**Issue by dannyeuu** [luminati-io/luminati-proxy#154]
I cannot open the proxy web, this error cause, even with upgraded version
![screenshot from 2018-12-04 13-20-39](https://user-images.githubusercontent.com/6808348/49452115-b3174780-f7c7-11e8-8cfd-f589958e081c.png)

**Comment by fudali** [comment]
Hi! I'm sorry I missed that issue. Please confirm if it's still relevant and if so then provide a bit more information on how to reproduce. Feel free to paste your configuration file **as long as you erase all the credentials** first
