### ISSUE TITLE
v1.113.585 Data center IP Lost

### ISSUE THREAD

**Issue by LiqiNew** [luminati-io/luminati-proxy#157]
hi！
Why after the version upgrade“,Data center IP” Features Lost?

**Comment by fudali** [comment]
Hi! Thanks for reaching out. It's because this option was redundant. You can achieve the same by going to the proxy port configuration page and then:
- 'IP control' tab
- 'Pool size'
- 'set from allocated IPs'
If the link doesn't appear there, make sure you have chosen 'Custom' preset first
