### ISSUE TITLE
How to get a proxy from command-line or Node.js API or Luminati REST API?

### ISSUE THREAD

**Issue by KolesnichenkoDS** [luminati-io/luminati-proxy#158]
I need to create a proxy in a specific zone automatically from my puppeteer bot written in Node.js and save it for further use. Seems that Node.js API doesn't work at all (or example in README.md is outdated).

**Comment by fudali** [comment]
When you run LPM it automatically exposes its API

You can find the documentation for it here:
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/luminati-io/luminati-proxy/master/lib/swagger.json#/Proxy/post_proxies
