### ISSUE TITLE
How to filter pictures or videos in SOCKS5 mode?

### ISSUE THREAD

**Issue by nostale** [luminati-io/luminati-proxy#159]
How to filter pictures or videos in SOCKS5 mode?

**Comment by fudali** [comment]
What do you mean by 'filtering'? 

- Do you want to filter out the requests in HAR viewer (the requests history)? If so then you can click an icon 'show/hide filters' and then apply the filter
- Do you want to send requests only when it's a picture or a video? Then the rule might be applied. If you need support the best way is to contact our support team https://luminati.io/#contact
