### ISSUE TITLE
Some websites do not work (Especially SSL)

### ISSUE THREAD

**Issue by maddo7** [luminati-io/luminati-proxy#16]
When accessing certain websites, for example http://live.com/ or https://live.com/, the proxy manager outputs errors and the site won't load:

INFO:24000: GET http://live.com/
DEBUG:24000: requesting using lum-customer-username-zone-gen-country-gb-session-24000_2
DEBUG:24000: GET http://live.com/ - 403
WARNING:24000: invalid proxy response { host: '178.62.26.154', code: 403, context: 'response' }

**Comment by lee-elenbaas** [comment]
live.com is blocked by the luminati service as a company policy to prevent possible spamming

**Comment by maddo7** [comment]
Is there a list of websites that are blocked?

**Comment by lee-elenbaas** [comment]
google and their assets, requesting ip instead of url - request will not go from the proxy peer - instead from the super proxy
web mail services, known malicious domains - completely banned
