### ISSUE TITLE
"possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit"

### ISSUE THREAD

**Issue by roshanzameer** [luminati-io/luminati-proxy#160]
The above message is logged in the console. Latest LPM, Node is used

**Comment by batrox** [comment]
I have the same issue

**Comment by fudali** [comment]
Can you share
- your configuration file **(without credentials)**
- a few URLs that you use
- a brief description on how you use LPM? Is it an automated scrapping or using through browser?

Also note that those are only warnings, it should not affect the behavior

**Comment by fudali** [comment]
I'm closing the issue due to inactivity. Please reopen whenever you want to provide more information
