### ISSUE TITLE
null_response examples

### ISSUE THREAD

**Issue by MarkusPint** [luminati-io/luminati-proxy#166]
There's 0 documentation anywhere about what's an acceptable URL regex. I've tried many globs and regexes, nothing works.

**Comment by fudali** [comment]
Hi @MarkusPint. What do you mean by globs? There's no documentation because it accepts all the regular expressions that you can think of. Regexp is not a term related to LPM. Also you can see on the right hand side what code your rule produces so you can be sure how it works exactly.
