### ISSUE TITLE
Error while starting proxy manager

### ISSUE THREAD

**Issue by SutharMukesh** [luminati-io/luminati-proxy#168]
I am stuck with this error when i start **Luminati-Proxy-Manager**
![image](https://user-images.githubusercontent.com/17264175/52617258-38526300-2ec1-11e9-85e5-4387d36d60c3.png)

Tried Re-installing the program, but no luck.

> here is my config

`
{
  "_defaults": {
    "customer": "",
    "password": "",
    "version": "1.122.334"
  },
  "proxies": [
    {
      "keep_alive": true,
      "last_preset_applied": "round_robin",
      "max_requests": 1,
      "override_headers": false,
      "pool_size": 10,
      "pool_type": "round-robin",
      "port": 24000,
      "session": true,
      "session_duration": 0
    }
  ]
}
`

**Comment by fudali** [comment]
This looks like a problem with your network configuration. Make sure you can load this url [http://lumtest.com/myip.json](http://lumtest.com/myip.json) from the same server you are running LPM.

If you have any other issues feel free to reopen
