### ISSUE TITLE
Some bug of luminati proxy manager

### ISSUE THREAD

**Issue by hotkingda** [luminati-io/luminati-proxy#17]
hello sir,
- we found that if we add the same port on the luminati proxy manager, the server will crash. Sometimes when we forget to refresh the page and add the same port, and server crash. 
- Another problem is that when we change to IP address, fro example, to get a new DE IP address, we need to delete the DE port first and then add again. Can you simplyfy this step? Such as add a buttom which can request new IP directly.
- Also, we found that when we get an IP address and open a website, when we delete the related port before close the website, server will crash. In another word, the server will crash when we delete the port from which the IP still sending some requests.

**Comment by lee-elenbaas** [comment]
Thanks just to make sure i have it all covered correctly:

1. adding a port that already exists causes the app to crush 

the latest version automatically place an avaliable port number in the dialog, so it should be easier - but can still happen - we will look into solving this

2. You want a new feature that will allow to refresh the IP from UI

feature on our doto list

3. if you delete a port while the browser is still open on that site - the app crush

can you tell me the version that this happens on - we made some changes in the last versions that should improve this behavior

**Comment by lee-elenbaas** [comment]
2. is now avaliable from version 0.7.9

**Comment by lee-elenbaas** [comment]
1. is now fixed with the new validations we added to the UI 0.8.37

**Comment by lee-elenbaas** [comment]
@hotkingda Can you please reproduce 3 for me in order to fix it - if you can't we will be able to close this report
