### ISSUE TITLE
LPM does not establish valid SOCKS5 connection

### ISSUE THREAD

**Issue by pgerlich** [luminati-io/luminati-proxy#170]
When attempting to run luminati (with or without the web manager), it fails to establish a valid SOCKS5 connection.

There are no errors, but when attempting to connect to a gaming client it fails to achieve a SOCKS5 connection to allow the client to begin a session. (all responses are 200 but the client fails to progress)

We have tried many approaches, but ultimately it doesn't work. In the meantime, we have moved to another service.

Here is our .luminati.json file:
```
{
  "_defaults": {
    "customer": "USER",
    "logs": 10000,
    "password": "PASS",
    "token": "TOKEN",
    "version": "1.123.411",
    "whitelist_ips": [
      "MY_IP"
    ],
    "www_whitelist_ips": [
      "MY_IP"
    ]
  },
  "proxies": [
    {
      "country": "us",
      "dns": "local",
      "iface": "0.0.0.0",
      "keep_alive": true,
      "max_requests": 0,
      "override_headers": true,
      "pool_size": 1,
      "pool_type": "round-robin",
      "port": 24000,
      "proxy": "servercountry-us.zproxy.lum-superproxy.io",
      "random_user_agent": true,
      "session": true,
      "session_duration": 0,
      "sticky_ip": true
    }
  ]
}
```

And the command line arguments I am giving it:
`luminati --log "info" --config ".luminati.json" &`

When I go to use the proxy, I am having to provide:
username/password (same as above)
IP: localhost
Port: 24000

On that note, the dropin mode doesn't seem to work correctly either.

Any help would be appreciated, I want to say we're doing something wrong but the documentation is sparse and often incorrect. In the meantime, we have stopped using the Luminati service.

**Comment by paulgerlich-wf** [comment]
Would be nice to get some attention. In the meantime, we've moved to ProxyRack as the SOCKS5 connection is usable and doesn't require an manager to route network traffic through.

**Comment by AhayOziel** [comment]
Hi @pgerlich

Luminati by default only supports ports 80 and 443. 
Usually gaming client are using different ports so I'm assuming that your issue is that you need to open those ports.
I order to open the port you need you'll need to contact your account manager.

**Comment by pgerlich** [comment]
Yeah we allegedly had the ports opened up by the account manager but the connections over socks5 don't work 🤷‍♂️

**Comment by rjpr** [comment]
I've run into a similar issue. Making SOCKS5 requests over port 43 (which is specifically mentioned as supported in the documentation) kind of works but does not properly close the session, so a request that should take 1 second takes 60+. The content is received during the request, it just doesn't close it immediately after it's received as it should.

You can reproduce this yourself using curl: 
`time echo test.eu | curl -v -x socks5://USERNAME:PASSWORD@localhost:24000 "telnet://whois.eu:43"`

Compare with the following (or use your own standard SOCKS5 proxy)
`time echo test.eu | curl -v "telnet://whois.eu:43"`

**Comment by AhayOziel** [comment]
Hi @pgerlich 

Luminati only supports SOCKS5 between the LPM and the machine that tries to open the connection.
After the LPM the SOCKS5 is being converted into HTTP/HTTPS request.
Because of that, if the target in your case the gaming client only accepts SOCKS connections, it will not work.

**Comment by pgerlich** [comment]
Don't think think that Luminati is false advertising then? I paid for the service under the sole pretense that they would support SOCKS5 connections, which they don't. It's a blatant lie.

**Comment by AhayOziel** [comment]
We apologize for making you feel like you were misled.
Here is the link to where we explain how the proxy manager process SOCKS5 protocol: https://luminati.io/learning-hub#socks5
Regardless you should contact your account manager, a lot of cases can be resolved on individual bases.

**Comment by pgerlich** [comment]
Yeah I read that and it wasn't terribly explicit. That is okay, though, I've moved on to a different proxy service. You should update that verbiage to explicitly state that the proxy manager does not forward the traffic on to the destination via SOCKS5 protocol.
