### ISSUE TITLE
WARNING: Updates Erase Configuration

### ISSUE THREAD

**Issue by askhogan** [luminati-io/luminati-proxy#171]
**Environment**

**Luminati Version Upgrading To:** 1.124.224
**Luminati Version On Before Upgrade:** 8 releases behind this according to orange banner
**OS:** Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1027-gcp x86_64)
**Host:** Google Compute Engine
**Server:** Awesome specs - 32GB of ram, 2TB SSD, ..... no resource limitation
**Node Version:** 10.15.1 (also tried this under Node 11 - see below)

***Problem (in use story form)***
As a user, I logged into the luminati proxy dashboard. Luminati displayed a big orange banner that said. "you are 8 releases behind, please click here to update." When a company makes updates that easy, if its on the weekends, I usually say, why not. I clicked the update button expecting a 4 minutes or so process. Luminati went through its update process. The following issues ensued:

***On Node 10***
1. My configuration was erased - starting me at a brand new screen saying "Add Proxy" - prior to this I had 9 specifically configured proxies. 
2. As I started to click around to various components of the Dashboard, I noticed it was very slow and started locking up the page to where I had to logout and re-login. I went into the update log and found several errors.
3. I tried to reinstall using `npm install -g @luminati-io/luminati-proxy` - but ran into the same issue as before. 
4. I thought perhaps this fresh version of Luminati needed some upgraded features in node or npm, so I used nvm to install Node 11.10.0. 

***On Node 11***
1. I used nvm to switch to node 11. I then did a clean install of Luminati. 
2. Luminati installed successfully but then threw off an error when I tried to start the binary and Luminati would not start - the error was "Error: No such module: timer_wrap"
3. At this point I figured being on Node 11 was introducing too many new variables, so I switched back to Node 10 using nvm. 

***Back on Node 10***
1. I switched back to Node 10.
2. I completely removed my node_modules folder and uninstalled node and npm 
3. I reinstalled node and installed my node modules again. 
4. I did a clean install of Luminati. This time it installed and I am now on the most recent version. 
5. The configuration that I had before is still erased and no where to be found. 
6. I am now going back and reconfiguring my luminati configuration that was deleted using Luminati's built in upgrade GUI click-through. 

**Conclusion/Advice**
Overall my advice is if you have Luminati working - do not upgrade - even though the GUI makes it seem like an easy process it is anything but easy and may break your entire config. If it aint broke, don't upgrade.

**Comment by fudali** [comment]
Hi @askhogan 

A note on Node 11: We don't support it. The official recommendation is to use Node 10 and it's mentioned on the README page

I'm sorry you had troubles with upgrading/downgrading and closing your config. We are about to introduce backup mechanism allowing for switching between many different configuration sets and making sure it's not lost when upgrading or doing anything else

**Comment by askhogan** [comment]
Thanks. The issue was on Node 10 the stable build. So the root issue started on Node 10. I only upgraded to Node 11 due to the node errors received after upgraded. The core issue I see was I followed the directions to a tee. I had the most stable version of node. I received a very simple upgrade option and the upgrade was anything but simple. There no backup. There was no rollback. The system was just broke.

**Comment by askhogan** [comment]
Even if the Node backup wasn’t there. At a minimum I would expect a complete copy of the version placed in some folder. The new version installed and then an alias link pointing to the new version, with the ability to easily switch back to the previous version by changing the alias (through an automated process where your upgrader detects failure)
