### ISSUE TITLE
Can't log in to the local control panel in China

### ISSUE THREAD

**Issue by nchstudio** [luminati-io/luminati-proxy#175]
luminati-china.io has been blocked in China, I have to visit it through a proxy. 
The luminati-proxy installed on my computer still works but I can't log in to its control panel. 
Is there anything I can do to bypass this log in restriction?
Thanks.

**Comment by saaryab** [comment]
Yes, you can use a different API address by adding the --api argument when starting the proxy manager. Please be in touch with your account manager or Luminati support to get a address that is not blocked.
