### ISSUE TITLE
Botched upgrades on dockerized LPM

### ISSUE THREAD

**Issue by sertys3** [luminati-io/luminati-proxy#178]
Hi team,
i'm running the LPM in docker and have update prompts on the navigation panel.
However when trying to upgrade the version of the app, i get in the console :
ERR: Error during upgrade: Error: User did not grant permission.
luminati    |     at /usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/sudo-prompt/index.js:134:23

I can only imagine this routine is again intended for LPM running non-containerized and requesting sudo access?
I'm also running node with uid 1000 and not root.

**Comment by sertys3** [comment]
I'm now 4 releases behind. Any possible relief for that issue in sight?

**Comment by fudali** [comment]
Currently there's no way to do an upgrade inside the docker. You need to download and use the new image.
