### ISSUE TITLE
LPM command app crashing

### ISSUE THREAD

**Issue by losawaru** [luminati-io/luminati-proxy#179]
Recently, I started to notice that the LPM command window is crashing and terminating. I have installed the latest version but the issue is still there. 

I've attached a screenshot of the LPM window with the errors I'm getting prior to the crash. The LPM is running on my Windows server 2012. 64 bits 

![Untitled](https://user-images.githubusercontent.com/48853734/54863900-2069cc80-4d14-11e9-9dd0-767ca56cf6b2.png)

**Comment by sertys3** [comment]
How many proxies you have there set?

**Comment by fudali** [comment]
Can you provide us with more information? How many requests are you sending? Can you also share your config file **(erase credentials first)** and what kind of URLs you use?

Basically any inforamtion that helps to reproduce the issue will be appreciated

**Comment by losawaru** [comment]
I'm using the LPM on a windows server and sending approximately 100-300 simultaneous requests. 

As I mentioned before, the LPM window wlll automatically close as soon as those errors/warnings start appearing. 

I have attached a text file of my config file. 
[config.txt](https://github.com/luminati-io/luminati-proxy/files/3010669/config.txt)

**Comment by losawaru** [comment]
Update:

I just updated the LPM to the latest version and it is still running at this point but getting the attached errors/warnings . Are these errors normal? I seem to be getting tons of these. 
![Capture](https://user-images.githubusercontent.com/48853734/55141766-be88d880-5100-11e9-8fd2-e7362fdea2f0.PNG)

**Comment by fudali** [comment]
Does LPM work correctly for you and the only issue are those logs now?

**Comment by losawaru** [comment]
I have 2 ports setup on the LPM ( One targeting Worldwide and the other only US). Only the Worldwide port is working. The port targeting US ( 24001) is not working. I can't access any target site using this port 24001.

![Capture](https://user-images.githubusercontent.com/48853734/55189623-eeb59300-5163-11e9-9aaa-0d5f6c395083.PNG)

**Comment by fudali** [comment]
Please contact me on skype krzysztof.fudali or use any other communication methods from luminati.io. This case is too specific to be able to debug it like this.

I'm closing this ticket. If I find any useful information for other people I'll share it in this topic
