### ISSUE TITLE
HTTPS behaviour over SOCKS5 needs documenting

### ISSUE THREAD

**Issue by tiyungjang** [luminati-io/luminati-proxy#18]
All HTTPS requests over SOCKS5 seem to exit with digital ocean IP addresses, ignoring country specification.

HTTPS requests made using the HTTP port of the same proxy always get correct IP addresses, as per the country specified in .luminati.json.

Plaintext HTTP requests made over SOCKS5 also get the correct IP addresses, as per the country specified in .luminati.json.

**Comment by tiyungjang** [comment]
After seeing #2 I guess this is more of a documentation issue. Perhaps show a warning when the user tries to use --country with --socks5 without specifying --resolve?

**Comment by lee-elenbaas** [comment]
good idea - i will add it

**Comment by lee-elenbaas** [comment]
Fixed on v0.7.33
