### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by Elite** [luminati-io/luminati-proxy#185]
Installed LPM and tried using it in my python script and here is the error:

` <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
`

**Comment by sertys3** [comment]
Are you trying to do SSL sniffing on your requests? 
There's a way to disable SSL certificate validation for your requests on urlopen() if you can't generate your own certificate.

**Comment by Elite** [comment]
> Are you trying to do SSL sniffing on your requests?
> There's a way to disable SSL certificate validation for your requests on urlopen() if you can't generate your own certificate.

Installed the luminati certificate file on my linux setup and it worked.
