### ISSUE TITLE
Default Proxy added when using config file (v0.7.31)

### ISSUE THREAD

**Issue by klunejko** [luminati-io/luminati-proxy#19]
Luminati started with following parameters:
`--www=1234 --customer=user--password=pw --database=db/db.sqlite3 --config=config/file.json`

file.json contains about ~100 proxies configurations. 

After starting the service, those 100 proxies are added correctly, but it also adds the default proxy:

port: 22225, sticky_ip: true, zone: gen, country: "", max requests: 50

**Comment by lee-elenbaas** [comment]
This is the intended behavior
to disable the drop-in proxy - you should add --no_dropin parameter to your command line

**Comment by klunejko** [comment]
Thanks, maybe the description could be updated to make this clear?

The current one doesn't make clear that's what happens:
`Disable drop-in mode for migrating`

**Comment by lee-elenbaas** [comment]
i have added http://luminati.io/faq#github-dropin
