### ISSUE TITLE
command line arguments on windows

### ISSUE THREAD

**Issue by x011** [luminati-io/luminati-proxy#192]
Hi there,

On Linux I can start `luminati  proxy manager` with:

`luminati --www_whitelist_ips "x.x.x.x" --www 64001 --dir /root/luminati_proxy_manager/ --session_duration 86400 --ssl true --sticky_ip true --zone "zone1" --pool_size 1 --customer "customer" --password "password" --keep_alive true --max_requests 500`

but on the windows version I cannot pass any command line arguments, I've tried:
`"C:\Users\USER\AppData\Local\Programs\@luminati-ioluminati-proxy\Luminati Proxy Manager.exe" /h`
and
`"C:\Users\USER\AppData\Local\Programs\@luminati-ioluminati-proxy\Luminati Proxy Manager.exe" --h`
 but L`uminati Proxy Manager.exe` ignores the cmdline arguments.

I've also tried editing: 
`"C:\Users\USER\AppData\Local\Programs\@luminati-ioluminati-proxy\luminati.json"`
  but the program, despite the fact that outputs: `"Loaded config C:\Users\USER\luminati_proxy_manager\luminati.json"`,  ignores it too.

How can I supply  command-line arguments on **proxy manager for windows** or load the `luminati.json` on start?

**Comment by AhayOziel** [comment]
@x011 It is possible.
All you need to do is to edit "Target" in the Luminati Proxy Manager shortcut's properties.
Change it from:
`%comspec% /C "C:\Users\ahay\AppData\Local\Programs\@luminati-ioluminati-proxy\Luminati^ Proxy^ Manager.exe" `
To:
`%comspec% /C "C:\Users\ahay\AppData\Local\Programs\@luminati-ioluminati-proxy\Luminati^ Proxy^ Manager.exe" --www 64001`
Or what ever you need.
