### ISSUE TITLE
New Socks5 server

### ISSUE THREAD

**Issue by m7ov** [luminati-io/luminati-proxy#2]
Found in this commit:
https://github.com/luminati-io/luminati-proxy/commit/a6d18d1b1753190d4ab2256d22aad44950872a73
SOCKS5 port (local:remote)

How to use this socks server? What is "remote"?
As I understand:
user -> socks -> luminati.

**Comment by giladno** [comment]
This option will setup a transparent SOCKS5 server which will redirect traffic to an instance of Luminati. 'local' port is the port for the SOCKS5 server to listen on, where 'remote' is the Luminati instance to redirect to. Assuming you're using the default setup (where the first local proxy will listen on port 23000), you can use `--socks 1234:23000` which will setup a SOCKS5 server on port 1234 and redirect its traffic to local port 23000.

**Comment by semiletov** [comment]
Great! Thanx for your reply. Everything working like a charm. I haven't only understand how to use one session. I want to use one IP for some period of time. But I get new IP every request.

**Comment by semiletov** [comment]
BTW when using --socks then --country for httpS doesn't work =( It will always US for all https requests. But for http it works fine.

**Comment by lee-elenbaas** [comment]
When using socks in order for HTTPS request to work properly you must provide a resolve file using the --resolve option to resolve IPs to hostnames
without it the HTTPS request can not know what host to open the connect session to

**Comment by m7ov** [comment]
Could you please give an example?
