### ISSUE TITLE
Please add city/asn to overview

### ISSUE THREAD

**Issue by klunejko** [luminati-io/luminati-proxy#21]
Previous versions showed the city and asn on the overview, the newest version just displays port, zone and country.

**Comment by lee-elenbaas** [comment]
We are planning to allow you to config the columns you want to show: by default we selected those columns: Port, zone, country, sticky ip & max requests
If anyone have a better suggestion for the default columns, we are open to hear it

**Comment by klunejko** [comment]
Ideally it would display those that are used in the configuration

**Comment by lee-elenbaas** [comment]
In the new versions have the ability to configure the columns
