### ISSUE TITLE
NPM Dependency Issue upon Installation

### ISSUE THREAD

**Issue by billedwards1890** [luminati-io/luminati-proxy#22]
Hi there,

When I try to install luminati via 'sudo npm install -g luminati-io/luminati-proxy', I get the following dependency errors:
/usr/local/bin/luminati-proxy -> /usr/local/lib/node_modules/luminati-proxy/bin/luminati.js
/usr/local/bin/luminati -> /usr/local/lib/node_modules/luminati-proxy/bin/luminati.js
/usr/local/lib
└─┬ luminati-proxy@0.8.1  (git://github.com/luminati-io/luminati-proxy.git#05a4ab0e8fc0fea5cca2bd435bf10034596bbf41)
  ├── UNMET PEER DEPENDENCY react@>=0.14.0
  └── UNMET PEER DEPENDENCY react-dom@>=0.14.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/luminati-proxy/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-redux@4.4.5 requires a peer of react@^0.14.0 || ^15.0.0-0 but none was installed.
npm WARN react-router@3.0.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-bootstrap@0.30.6 requires a peer of react@>=0.14.0 but none was installed.
npm WARN react-bootstrap@0.30.6 requires a peer of react-dom@>=0.14.0 but none was installed.
npm WARN react-overlays@0.6.10 requires a peer of react@>=0.14.0 but none was installed.
npm WARN react-overlays@0.6.10 requires a peer of react-dom@>=0.14.0 but none was installed.
npm WARN react-prop-types@0.4.0 requires a peer of react@>=0.14.0 but none was installed.
npm WARN uncontrollable@4.0.3 requires a peer of react@>=0.11.0 but none was installed.

I currently have react@15.3.2 installed, and I've tried uninstalling react and downgrading to 0.14.0 but get the same error. Please help!

**Comment by boxbeatsy** [comment]
If it helps, I was trying to upgrade luminati, and now when I run the 'luminati' command I get the following error:

module.js:474
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

**Comment by billedwards1890** [comment]
If it helps, this occurred after trying to upgrade luminati to the latest version.  Now, when I run luminati, I get the following error:

module.js:474
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

**Comment by lee-elenbaas** [comment]
If upgrade does not help - do uninstall

    npm uninstall -g luminati-io/luminati-proxy

and then reinstall

   npm install -g luminati-io/luminati-proxy

**Comment by billedwards1890** [comment]
Hi Lee, I've tried uninstalling and reinstalling.

I'm still getting the same error:   ├── UNMET PEER DEPENDENCY react@>=0.14.0
  └── UNMET PEER DEPENDENCY react-dom@>=0.14.0

When I check react version with the command "sudo npm list | grep react", I get the following result which makes it seem like react is installed.  Any thoughts on what could be going wrong?

│ ├─┬ babel-preset-react@6.16.0
│ │ ├── babel-plugin-transform-react-display-name@6.8.0
│ │ ├─┬ babel-plugin-transform-react-jsx@6.8.0
│ │ │ └── babel-helper-builder-react-jsx@6.18.0
│ │ ├── babel-plugin-transform-react-jsx-self@6.11.0
│ │ └── babel-plugin-transform-react-jsx-source@6.9.0
│ ├─┬ react-bootstrap@0.30.6
│ │ ├── react-overlays@0.6.10
│ │ ├── react-prop-types@0.4.0
│ ├── react-lite@0.15.26
│ ├─┬ react-redux@4.4.5
│ │ └── hoist-non-react-statics@1.2.0
│ ├─┬ react-router@3.0.0
├─┬ react@15.3.2
└── react-dom@15.3.2

**Comment by billedwards1890** [comment]
I ended up solving this by running 'npm uninstall -g' followed by 'npm install -g luminati-io/luminati-proxy'.  It seems like there was another installed package that needed to be reinstalled other than luminati and react.  Thank you!
