### ISSUE TITLE
Trouble connecting to SSL endpoints via Luminati Proxy Manager

### ISSUE THREAD

**Issue by billedwards1890** [luminati-io/luminati-proxy#23]
We are seeing intermittent 'CONNECT' errors when trying to access https URL's through luminati's proxy manager.

We are using the default settings when starting up the proxy manager (just the command luminati')

The errors seem to occur in spurts at random.

Server output:
admin is available at http://127.0.0.1:23000
2016-11-09T02:06:55.893Z - 24000 - error: CONNECT whats-my-ip.herokuapp.com:443 - 502
2016-11-09T02:06:58.594Z - 24000 - error: CONNECT whats-my-ip.herokuapp.com:443 - 502
2016-11-09T02:07:00.232Z - 24000 - error: CONNECT whats-my-ip.herokuapp.com:443 - 502
2016-11-09T02:07:02.178Z - 24000 - error: CONNECT whats-my-ip.herokuapp.com:443 - 502

The odd thing is the intermittent nature.  We can run the same command 'curl -x 127.0.0.1:24000 "https://whats-my-ip.herokuapp.com/text"' repeatedly, and some fraction of requests will error out.

**Comment by lee-elenbaas** [comment]
What is the error rate you are getting? how many success/failures?

**Comment by boxbeatsy** [comment]
The errors come in spurts.  I'd say the overall success rate on our https requests is high (~ 95%).  However, during certain time intervals, the error rate appears to go up to 100%.

**Comment by billedwards1890** [comment]
The errors come in spurts. I'd say the overall success rate on our https requests is high (~ 95%). However, during certain time intervals, the error rate appears to go up to 100%.

**Comment by lee-elenbaas** [comment]
~95% seems ok - can you contact your luminati success and check the times that yuo get more errors with him?
