### ISSUE TITLE
0.8.32 is breaking the admin

### ISSUE THREAD

**Issue by iamwiliam** [luminati-io/luminati-proxy#24]
@Orhann21 The last version 0.8.32 is breaking the admin. I can't save because some validations fails. 

For example: defaults.zones is not populated, so I can't save.

**Comment by lee-elenbaas** [comment]
Thanks for pointing out - will be fixed soon

**Comment by iamwiliam** [comment]
The bug is still there at 0.8.36:

Missing zones:
http://i.imgur.com/deYxttj.png

This time, you can save, the zone will be the default one "gen" and there aren't console messages, only a validation warning of "gen" value:

`The specified value "gen" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?`

**Comment by lee-elenbaas** [comment]
The new version 0.8.37 should solve the issue
