### ISSUE TITLE
[Request feature] Control proxy behaviour for individual requests via header.

### ISSUE THREAD

**Issue by iamwiliam** [luminati-io/luminati-proxy#26]
It would be useful if we can control the proxy behaviour for individual requests. For example:

```
Direct Request:
==========
GET http://lumtest.com/myip.json
Headers:
- x-hola-flag-direct: true

Expected behaviour: bypass peer and let super proxy connect with lumtest.com
```

```
ByPass Request:
==========
GET http://lumtest.com/myip.json
Headers:
- x-hola-flag-bypass: true

Expected behaviour: bypass superproxy and let proxy manager connect with lumtest.com directly
```

```
Null Request:
==========
GET http://lumtest.com/myip.json
Headers:
- x-hola-flag-nullify: true

Expected behaviour: return directly NULL (it's usefull when you only can add headers, for example in electron, you can cancel the request, modify headers but you can't change the response or nullify it)
```

```
Session requests:
==========
GET http://lumtest.com/myip.json
Headers:
- x-hola-session: asd123

Expected behaviour: maintain the ip for requests with the same session
```

Other useful features would be:
- select dns-local and dns-remote "x-hola-flag-dns: local"
- select country or city ip "x-hola-flag-country" or "x-hola-flag-city"
- drop session after receive header "x-hola-flag-drop-session"

**Comment by lee-elenbaas** [comment]
I want to understand the need, since you currently have ways to do all of those operations, why those methods are not enough?

today you can already:

- trigger the first 3 (direct, bypass & null) using regular expressions, that will allow you to be as specific as you want.

- session, dns, country, city - you can use the allow_proxy_auth and use the proxy authorization to specify each of them for every request you want to (you can also specify direct here).

- drop session - you currently have two options: using the PM refresh_sessions endpoint, or use the the hola_trigger option, but if you already control the session in your code, just drop it and let it die after 60sec on the hola servers

**Comment by iamwiliam** [comment]
@lee-elenbaas there is any documentation of "Allow request authentication"? I suppose that it asks for authentication and send it to the super proxy. Will this affect to the performance?

And any documentation for "hola_trigger"?

The need is to let the application to decide when direct, bypass or null a request and not in the proxy-manager.

For us is easier and cleaner have that logic in the application (and goes to the repository) than put project logic inside the PROXY app.

And thanks for your fast response and your time.

**Comment by lee-elenbaas** [comment]
allow_proxy_auth is the option you can turn it on using the UI or using the CLI
it means that if the request contains proxy-authorization header - it is passed over to the super-proxy as is
so you can use all that the luminati API allows you to use directly https://luminati.io/cp/api_example

the hola_trigger is also documented on https://luminati.io/cp/api_example#hola_trigger

please contact your luminati rep for more info then that

even with the current setup - it is possible to keep the proxy-manager config file as part of your source control, or even configure it from your code using REST, will this answer your need to keep it all in the same place?

**Comment by iamwiliam** [comment]
I see, I can embed proxy in the app or change config using REST api. It's a good idea.

Thanks, I will check the doc.

**Comment by lee-elenbaas** [comment]
What is the technology you use to create your app?

**Comment by iamwiliam** [comment]
Nodejs. I saw the doc of proxy manager, but now we have the proxy centralized in a standalone machine.

**Comment by lee-elenbaas** [comment]
nodejs then you can simply use the proxy manager as a required module
