### ISSUE TITLE
[Request feature] Why --direct_include has been remove?

### ISSUE THREAD

**Issue by iamwiliam** [luminati-io/luminati-proxy#28]
Bypass proxy exposes the crawling machines, --direct_include is fast but don't exposes crawling machines.

Why has been removed?

**Comment by lee-elenbaas** [comment]
We have not seen use of this feature - so we removed it from the proxy manager
i will bring it back up to our product team to decide whether to bring that feature back into the proxy manager

if there is anyone else who was using this feature - please let us know

**Comment by iamwiliam** [comment]
Direct and bypass are useful for us.

We use bypass for assets in public cdn and direct for private cdn assets. We don't need multiple ips for the assets but we don't want to expose our crawling machine ips.

We use "electron" for crawling so is not easy to setup a GEN proxy for common connections and STATIC for assets, so DIRECT and BYPASS are useful for fast crawling.

**Comment by lee-elenbaas** [comment]
@iamwiliam can you please contact your luminati success manager and inform him about your need - it will help push this forward

**Comment by lee-elenbaas** [comment]
direct requests have been readded into the proxy manager as of version 0.9.34
