### ISSUE TITLE
resolve file problem.

### ISSUE THREAD

**Issue by yuxden2** [luminati-io/luminati-proxy#29]
Hi Team:

i got an warning when add socks:
SOCKS without using a resolve file will make HTTPS requests from the super proxy and not from the proxy peer

Can I know the detail of this warnning?

**Comment by lee-elenbaas** [comment]
Our SOCKs interface provide a wrapper around our HTTP(S) proxy service, since the HTTPS proxy require the host header, but the SOCKs layer gives only the IP, we need a way to translate the requested IP to hostname
without it SSL tunneling can not be established properly
The resolve file is how to provide the proxy manager a way to resolve the IPs back into hostnames
use --resolve <file-path> for it.
The UI provide an editor that will allow you to add domains into the file in an easy way

**Comment by yuxden2** [comment]
So do you mean if I add --resolve

I can connect https request with proxy ip not the peer ip?

**Comment by lee-elenbaas** [comment]
if you add resolve file - and configure in it all the domains that you are using, then requests will come to the target site from the proxy peer, and not from the super proxy

**Comment by pala1220** [comment]
@lee-elenbaas . The same issue faced. I can not find the editor in the UI, where it can be found?  And what is a resolve file? A file like "C:\Windows\System32\drivers\etc\hosts", or something else? Can you share one? Thank you  so much.

**Comment by lee-elenbaas** [comment]
the syntax is very much like that of the hosts file

just add --resolve <path> to the command line and you should be able to edit it from the tools page

**Comment by pala1220** [comment]
I start luminati-proxy with the command: luminati --resolve c:\resolve.txt
c:\resolve.txt is an emputy file I created.
In the Tools page, it can only edit the file C:\Users\Administrator\luminati.json
What should I add into the file resolve.txt?
1.2.3.4 github.com ?
seems not work.

**Comment by lee-elenbaas** [comment]
When i specify a file in the config file, or using the command line: --resolve <path>
i get this editor:
![image](https://cloud.githubusercontent.com/assets/465641/21381081/e2cb408c-c761-11e6-99ed-e163b538b012.png)

you can contact your luminati success manager to get a faster response

**Comment by pala1220** [comment]
![tools](https://cloud.githubusercontent.com/assets/24687958/21381850/a2c192ac-c798-11e6-9470-747d2bafd285.png)
 Something wrong? Have reinstalled luminati-proxy.

**Comment by lee-elenbaas** [comment]
What was the command line parameters used?

in my case i used: luminati --resolve c:\resolve.txt

**Comment by pala1220** [comment]
Reinstalled again, browser cleared.
start with: luminati --resolve c:\resolve.txt
No "IP resolution file" editor found in Tools.
Whats wrong?!!

**Comment by lee-elenbaas** [comment]
@pala1220 please contact you luminati success manager, and have an online session with him

**Comment by pala1220** [comment]
@lee-elenbaas  ok, thank you.

**Comment by yuxden2** [comment]
@lee-elenbaas I only add --resolve,so I find nothing in the panel,Can you add the format in the readme?

**Comment by vicngtor** [comment]
I also have this problem. Am I expected to populate the resolve file myself?

**Comment by lee-elenbaas** [comment]
I have added documentation and sample file on the FAQ https://luminati.io/faq#proxy-socks
