### ISSUE TITLE
Allow use as a module

### ISSUE THREAD

**Issue by EndangeredMassa** [luminati-io/luminati-proxy#3]
If I already have a Node.js program to make requests through Luminati, it would be great to be able to use this library as a way to make my requests to take advantage of these features. That way, I wouldn't have to put another proxy between my client and the target.

Something like this would be great:

```js
const Luminati = require('luminati-proxy');

const options = {customer: 'abc', password: '123', ...};
const proxy = new Luminati(options);

// ...

const url = 'http://google.com/whatever';
proxy.request(url, (error, response) => {
  // handle response
});
```

**Comment by lee-elenbaas** [comment]
It is planned - will take some time

**Comment by lee-elenbaas** [comment]
Supported since version 0.3.0
