### ISSUE TITLE
LUMINATI PROXY KEEPS CRASHING

### ISSUE THREAD

**Issue by yssvic** [luminati-io/luminati-proxy#31]
Hello, 

This is the exception, can't you make the code so it restarts automatically when this exception is being thrown? It keeps crashing, very problematic since everything stops then. 

Cheers. 

2017-01-11T18:04:32.063Z - 24001 - warn: invalid proxy response
host=XXX.XXX.XXX.XXX, code=502, context=connect
Shutdown, reason is uncaughtException, error = Error: write EIO
2017-01-11T18:04:32.070Z - 22999 - info: Stopping proxies 0=24000
2017-01-11T18:04:32.072Z - 22999 - info: Stopping proxies 0=24001
2017-01-11T18:04:32.077Z - 22999 - info: Manager stopped
reason=uncaughtException, error = Error: write EIO, force=true,
restart=undefined

**Comment by lee-elenbaas** [comment]
@yssvic if you can run it with the --log silly command line argument - it will provide more information to try and track down the issue

If you want it to restart itself, you can start it in daemon mode using the --daemon command line argument

**Comment by yssvic** [comment]
Hello, Thank you for your message. 

I'm running it now with --log silly and logging it to file so if it crashes i can send you the log dump.
 
OS I'm using for this server is UBUNTU VERSION="16.04.1 LTS (Xenial Xerus)"

About your --daemon command. How do I know the server is down, and how does the --daemon command will restart the service when it's down? Please advise. 

Cheers,

**Comment by lee-elenbaas** [comment]
Our daemon mode uses [pm2 ](http://pm2.keymetrics.io/) under the hood
in order to have full monitoring capabilities, install pm2 and use their commands

right now we only offer to start the daemon using --daemon
and to stop the daemon using --stop-daemon
