### ISSUE TITLE
Urgent request

### ISSUE THREAD

**Issue by hotkingda** [luminati-io/luminati-proxy#33]
![temp_9222a83b-3654-4945-a2d7-0b501d10adc9](https://cloud.githubusercontent.com/assets/22517452/22968939/7d07d464-f3a7-11e6-8f89-1ab873c18ac6.png)

Hello Buddy,

My new version Luminati switched on the SSL and it already uesd reverse_lookup_dns. It can open the page but not posting the data though. Anyone can help me solve this issue? Also, if there are more than 10 people using the http://server ip:22999, less than 1 min it will be an error. 

Thanks for the help,

Matty

**Comment by jaspax** [comment]
Hi, hotkinda,

Can you give me the command line that you're using to launch the proxy, and the way which you're accessing the proxy?
