### ISSUE TITLE
Proxy Manager Crashing on server

### ISSUE THREAD

**Issue by thecoolhascome** [luminati-io/luminati-proxy#45]
Hello, i am running proxy manager on windows server 2012 R2, and when I had around 1,000 proxies running on a zone (gen) and whenever I had many requests coming from these proxies, it would crash, and I would need to restart it.. help would be greatly appriciated, Thanks

**Comment by ovidiuD** [comment]
Hi, can you tell me the command use to run the manager along with a short usage script that would help reproduce the issue? also what version are you on currently?

**Comment by thecoolhascome** [comment]
Im on the latest version... i use the command "luminati" to run the script... where would i find a usage script?

**Comment by ovidiuD** [comment]
Hi you can do ```luminati --help``` to see all options supported

Pe 3 mai 2017 7:41 PM, "thecoolhascome" <notifications@github.com> a scris:

**Comment by thecoolhascome** [comment]
Ok, Does the CPU and other specs also determine how good the manager runs or if it wont crash.... for example.. If i was to run 1000 proxies on a very small processor.. would it affect how its ran?

**Comment by ovidiuD** [comment]
Hi can you upgrade to last version, 0.10.13 in case you're on an older version, also run with luminati --log debug and save all output to a log file; send me the long when it crashes again please.
Yes cpu and memory usage increases with that many proxies opened and with number of simultaneous requests. When you say 1000 proxies, you mean 1000 ports opened on the same manager instance? how do you open them? api/config/interface?

**Comment by thecoolhascome** [comment]
I open the ports in the interface... Here is a screenshot of the error i recieved which made proxy manager crash - this was on a good CPU ubuntu server and I could barely get 15 proxies running
<img width="678" alt="screen shot 2017-05-04 at 10 07 36 am" src="https://cloud.githubusercontent.com/assets/28245871/25707922/fbd57f4c-30b2-11e7-823a-2209dd6a5e68.png">

**Comment by ovidiuD** [comment]
Looks like you're trying to open a port which is already in use, or you have multiple instances running
Anyway it's a port conflict - make sure all your proxies have unique ports

**Comment by yssvic** [comment]
Also if you want to handle load of 1000's of concurrent sessions I would load balance it to different proxy managers, that's what I did using HAProxy.

**Comment by thecoolhascome** [comment]
Could you give me some knowledge on what HAproxy is?

**Comment by ovidiuD** [comment]
HAproxy is a load balancer, you need some good level of understanding on how it works in order to make good use of it. http://www.haproxy.org/

**Comment by thecoolhascome** [comment]
Ok, Great - Thanks for all the help... everythings working great
