### ISSUE TITLE
Start Luminati On Server Boot

### ISSUE THREAD

**Issue by thecoolhascome** [luminati-io/luminati-proxy#46]
Hello, i am currently using proxy manager on an AWS c4.2xlarge server on Ubuntu 14.04 LTS (Server) I was wondering if there is a way to make the luminati proxy manager start automatically when i boot up the server rather than me having to SSH into it and run manually. 

Thanks, John

**Comment by ovidiuD** [comment]
Hi,
this should work https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04#manage-application-with-pm2
first run luminati as daemon ```luminati -d```
then make sure pm2 sees the app ```pm2 list```
then to set it at startup ```pm2 startup``` and run the command it outputs

**Comment by thecoolhascome** [comment]
Hi, I used all of these commands, and once i entered the command which `pm2 startup` outputs, and the process finished, I terminated the ssh, and restarted the server... when i restarted the server and tried connecting to the proxy manager, It did not work.

**Comment by ovidiuD** [comment]
After restart does pm2 list show luminati in it?
Did you start luminati as daemon before upstart command?

Pe 13 mai 2017 05:57, "thecoolhascome" <notifications@github.com> a scris:

**Comment by thecoolhascome** [comment]
yes, and yes

**Comment by ovidiuD** [comment]
try ```pm2 save``` after starting luminati as daemon, then do ```pm2 startup```.

**Comment by thecoolhascome** [comment]
Hey, I just figured this out. i used a command called `tmux` and then typed in `luminati`after entering that.... be sure to check it out. Thanks!
