### ISSUE TITLE
Whitelist Certain Websites to proxies

### ISSUE THREAD

**Issue by thecoolhascome** [luminati-io/luminati-proxy#49]
Hello, I was wondering if there is a way to whitelist websites to my proxies

example:

I only want this website to be accessible from my proxies: 

https://coolwebsite.com

**Comment by ovidiuD** [comment]
Hi, there is no such option right now. There is only possibility of passing a bypass proxy option. If you know some urls that you want to not go through the proxy, you can setup a regular expression and pass it to ```--bypass_proxy``` parameter.

**Comment by thecoolhascome** [comment]
Ok, thanks so much.. I would definitely recommend you add this to the proxy manager as it would help many people.. thank!]s!
