### ISSUE TITLE
proxy crashes after running under some load for a while

### ISSUE THREAD

**Issue by erans** [luminati-io/luminati-proxy#5]
I run the proxy with a pool of 5. Under some load it simply crashes with the error:

events.js:141
      throw er; // Unhandled 'error' event

I also ran it with logging set to DEBUG but it didn't give a lot more information.

It happened in the older version (the one before the last) and with the latest one.

Are you aware of that? do you have any solution?

**Comment by lee-elenbaas** [comment]
version 0.2.9 supposed to handle that - and also collect more information so we can fix it if you run it with --log DEBUG
