### ISSUE TITLE
Not persistent configuration for static zone

### ISSUE THREAD

**Issue by koprivajakub** [luminati-io/luminati-proxy#50]
Hi,

today I noticed the `max_requests` parameter does not write it's not default value to the configuration file. We are running multiple servers and we do copy paste the configuration from the GUI `tools > configuration file`. The parameter max_requests is written there for every zone except the one named `static`. We did set the value from `0` which was default value when we created the proxy to value `50`. This is a big issue for us because we have to double check the configuration on all servers after the luminati manager get restarted.

**Comment by ovidiuD** [comment]
Hi,
all default values are not saved in the configuration file. even if set explicitly, if they match the default, they will not be stored.
if by zone named ```static``` you mean the one with port 22225, that's a dropin replacement for direct API access. This proxy's settings cannot be modified, if you go to /proxies in the GUI you will see this behavior. Even setting it manually in the ```tools > configuration``` won't stick, it will revert to it's default settings.
If you don't use this port ```22225```, you can disable it completely using ```--no-dropin``` command line parameter.

**Comment by koprivajakub** [comment]
OK, thanks
