### ISSUE TITLE
UI Login overwrites config with default

### ISSUE THREAD

**Issue by klunejko** [luminati-io/luminati-proxy#54]
We generate our config on deployment and until we upgraded to v0.10.x we had no issues (we stuck with 0.7.33 for a while). However with v0.10.16, v0.10.17 and v0.10.18, once we log in to the web interface, the _defaults credentials get overwritten.

We also tried adding the zone/pw to each proxy entry, but it looks like the proxy manager discards those upon startup.

Right now we basically have to deploy twice. Deploy, log in, then remember to deploy again (since the config isn't touched once the cookie or w/e is present). And if the second step is overlooked, it takes all of our proxies offline.

Ideally, logging in would do nothing if _defaults is set. If that's not possible, can you add a custom flag that indicates to the proxy-manager not to touch the config?

----------

Deployment Config
```
{
  "_defaults": {
    "customer": "user",
    "password": "zone-pw",
    "zone": "zone-id"
  },
  "proxies": [
    {
      "customer": "user",
      "password": "zone-pw",
      "zone": "zone-id",      
      "country": "xx",
      "proxy": "xx"
    }
  ]
} 
```

Config once proxy-manager is running
```
{
  "_defaults": {
    "customer": "user",
    "password": "zone-pw",
    "zone": "zone-id"
  },
  "proxies": [
    {
      "country": "xx",
      "proxy": "xx"
    }
  ]
}
```

Config after login
```
{
  "_defaults": {
    "customer": "user",
    "password": "account-pw",
    "zone": "gen"
  },
  "proxies": [
    {
      "country": "xx",
      "proxy": "xx"
    }
  ]
}
```

**Comment by kacepe** [comment]
Can you provide your startup params?
