### ISSUE TITLE
need some help setting up on linux

### ISSUE THREAD

**Issue by TheGoonZ** [luminati-io/luminati-proxy#56]
Hello everyone, i am in need of help setting up lum on a linux server, ive tried everything and can not get it to work. I will be using digital ocean or linode for the server, im willing to pay for help on doing this. if this is something you could do please leave a post below and i will send you my skype, thanks.

**Comment by ovidiuD** [comment]
Hi, can you give more info on what is the problem you're currently experiencing, the linux os, version and node version?

**Comment by mrbboy** [comment]
I 've got mine running on linux let me know if you need help

**Comment by TheGoonZ** [comment]
Hi i do need help, do you have skype/discord? let me know thanks. im
willing to pay!

**Comment by TheGoonZ** [comment]
Hi, i still need this. let me know if you guys can help me install it on
linux, ill pay. thanks

**Comment by ranle** [comment]
hi @TheGoonZ, what's your Luminati username?

**Comment by mrbboy** [comment]
@TheGoonZ Im sure people at Luminati can assist you, they 've been very helpful and responsive in my situation, but if you need my help for installing on linux this is my skype -> george_br21
