### ISSUE TITLE
Docker installation instructions

### ISSUE THREAD

**Issue by brandomr** [luminati-io/luminati-proxy#57]
I think that the docker installation instructions should include the fact that to access the admin panel you must forward the port with:
```
docker run -p 22999:22999 luminati/luminati-proxy luminati 
```
Then you can access the admin panel at localhost:22999

**Comment by ovidiuD** [comment]
Hi, Yes without forwarding the port can't be accessed, also any proxy port should be forwarded as well.
Will update the instructions, thanks for your input.

**Comment by janhjordie** [comment]
@ovidiuD  The documentation on https://github.com/luminati-io/luminati-proxy is still not updated ??
Could you please update it. It's very frustrating the basic manual is incomplete and being new in this docker stuff
