### ISSUE TITLE
assistance with installation on linux machine using terminal

### ISSUE THREAD

**Issue by Tienngo98** [luminati-io/luminati-proxy#58]
Hi, can i get some assistance setting up luminati on ubuntu 16.04 using terminal. I installed luminati proxy manager, but how do i access it to create proxies without a gui or is there a way to do this?

**Comment by ovidiuD** [comment]
Hi,
To access the UI, open 127.0.0.1:22999 in browser. If it's on a headless server and can't open 22999 to outside, you have the option to use command line parameters or a config file, by default located at ~/.luminati.json
To get help about all command line parameters use ```luminati -h```
