### ISSUE TITLE
ERROR: uncaughtException

### ISSUE THREAD

**Issue by yuxden** [luminati-io/luminati-proxy#6]
Hi:

I use in windows 10 64bit,Sometime It show this error:

ERROR: uncaughtException { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

Can I know how can I fix that?

Thank you!

**Comment by lee-elenbaas** [comment]
what version are you using?

**Comment by yuxden** [comment]
Hi, @lee-elenbaas it's version 0.211

**Comment by lee-elenbaas** [comment]
Please upgrade, should not some the problem, but should give more
information so we will be able to solve it
