### ISSUE TITLE
Restart Luminati with Monit

### ISSUE THREAD

**Issue by Julienh** [luminati-io/luminati-proxy#60]
Hi,
Is it possible to restart Luminati with Monit when Luminati crash? I tried but it can't restart
Thanks

**Comment by thecoolhascome** [comment]
I second this - would be great

maybe a linux command that restarts a program

**Comment by ranle** [comment]
Hi @Julienh and @thecoolhascome. did you try running luminati with the --daemon parameter? if for some reason the proxy manager crashes, it should restart the instance.

**Comment by Julienh** [comment]
Hi @ranle , sometimes it's not restart, but since I updated it's seems to be OK, for now

**Comment by ranle** [comment]
Ok. Feel free to reopen this issue if the error persists.
