### ISSUE TITLE
Installing ProxyManager on Ubuntu (16.04) 

### ISSUE THREAD

**Issue by KobeGlobal** [luminati-io/luminati-proxy#62]
**I first ran the following command:** 
sudo npm install -g luminati-io/luminati-proxy

**Once it's done, I got this warning:**
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/luminati-proxy/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**And when I typed 'luminati' or 'luminati --help' on the console, I get this:**
Installation problem was detected (sqlite3 package, reason: Cannot find module '/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node').
Please run the following command to recover:
sudo rm -rf /usr/local/lib/node_modules/luminati-proxy/node_modules && sudo npm install -g luminati-io/luminati-proxy

However, running the command didn't recover anything.

Could use a little help on how to use the ProxyManager :)

**Comment by Eloverflow** [comment]
Try to: 
cd /usr/local/lib/node_modules/luminati-proxy
sudo rm -rf node_modules/
sudo npm uninstall sqlite3

And then:
sudo npm install -g @luminati-io/luminati-proxy
