### ISSUE TITLE
407 Auth Error

### ISSUE THREAD

**Issue by yuxden** [luminati-io/luminati-proxy#65]
Hi;

I just install new version of Luminati proxy manage with Window10.

But I got an 407 error all the time.

Can you help me to solve it?

Thank you!

**Comment by sk91** [comment]
Hi,
Please send me your customer id or contact details to maximk@luminati.io and we will check it out.

**Comment by yuxden2** [comment]
@sk91 Have send email.

**Comment by idb-** [comment]
am having the same issue when using lp as a gateway connection through fiddler. 407 100% of the time.

**Comment by lijijordan** [comment]
am having the same issue when using lp as a gateway connection through fiddler. 407 100% of the time.

**Comment by sk91** [comment]
Hi,
This is an individual issue, you should contact your success managers for that

**Comment by yuxden2** [comment]
I have try many time,it happen in all my win10 device.

**Comment by idb-** [comment]
How is this an individual issue when multiple people are having it?

**Comment by liangecc** [comment]
too much 407 error, +1.
