### ISSUE TITLE
Super Proxy Help

### ISSUE THREAD

**Issue by thecoolhascome** [luminati-io/luminati-proxy#69]
Hello, Currently I am trying to make a super proxy have a short username, and instead of going through "zproxy.luminati.io" i want it to go through my own web address.

i have tried starting luminati up by typing `luminati --proxy mywebsite.com --short_username username`

this does not work and the proxies fail when i launch it this way

please let me know how i can get this to work. thank you!

**Comment by sk91** [comment]
Hi,
Luminati proxy manager can work only with a luminati proxy server. Custom proxy server are not supported.
