### ISSUE TITLE
Support additional ports to maintain sessions

### ISSUE THREAD

**Issue by maddo7** [luminati-io/luminati-proxy#7]
This tool is great to link luminati with various apps as they often fail to use the standard values and simply mark the proxy as dead.

Now I didn't manage to maintain the IPs in multiple sessions with this tool like it would be possible with the -session- parameter.

Requetsts either change the IP too often or multiple requests of the same kind have the same IP with --sticky_ip wich isn't ideal either.

Would it be possible to open several ports specified by the user like 24000 - 25000
and every request to the same port maintains one session and therefore one IP if possible.

**Comment by lee-elenbaas** [comment]
The tool already support configuring multiple proxies on different ports
you can do it from a config file
from the WebUI (by default http://120.0.0.1:22999/)
or from the RestAPI that powers behind the WebUI
