### ISSUE TITLE
Install Script Overwrites Global Git Setup

### ISSUE THREAD

**Issue by thisjustin** [luminati-io/luminati-proxy#71]
After running the install script (https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh) I was unable to authenticate with git over ssh, all my git urls kept getting changed to start with `git+https` which resulted in the error `fatal: Unable to find remote helper for 'git+https'` any time I tried to fetch or push to my remotes.

The fix was to `git config -e --global` and comment out the lines like (you could also just remove them):
```
#[url "git+https://github.com/"]
#       insteadOf = git@github.com:
#[url "git+https://"]
#       insteadOf = git://
```
but ideally the install script should remove these after it's done.

The lines in `lpm_clean` shown below are what add the config:
```
git config --global url."git+https://github.com/".insteadOf git@github.com:
git config --global url."git+https://".insteadOf git://
```
and they should be reverted at the end of the install process.

If Luminati somehow needs this change on an ongoing basis then that should be noted somewhere in install docs and a workaround for git users using ssh should be documented.

**Comment by sk91** [comment]
You are correct. We will fix it.
