### ISSUE TITLE
Unable to install proxy manager

### ISSUE THREAD

**Issue by vijay-axis** [luminati-io/luminati-proxy#72]
Ubuntu 14.04
Node.js v6.12.0
Git 1.9.1

Error Stack
/usr/lib
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@luminati-io/luminati-proxy/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.13.0-132-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@luminati-io/luminati-proxy"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/.staging/sprintf-b2430ad9
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/sprintf-b2430ad9' -> '/usr/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/node_modules/ipv6/node_modules/sprintf'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/sprintf-b2430ad9' -> '/usr/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/node_modules/ipv6/node_modules/sprintf'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vijay/npm-debug.log
npm ERR! code 1

**Comment by OskHa** [comment]
Same issues.

```
45678 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@luminati-io/luminati-proxy/node_modules/chokidar/node_modules/fsevents):
45679 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
45680 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
45680 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
45680 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
45680 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
45681 verbose stack Error: ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/sprintf-b2430ad9' -> '/usr/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/node_modules/ipv6/node_modules/sprintf'
45681 verbose stack     at destStatted (/usr/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
45681 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:264:29
45681 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
45681 verbose stack
45681 verbose stack Error: ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/sprintf-b2430ad9' -> '/usr/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/node_modules/ipv6/node_modules/sprintf'
45681 verbose stack     at Error (native)
45682 verbose cwd /home/ubuntu
45683 error Linux 3.13.0-44-generic
45684 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@luminati-io/luminati-proxy"
45685 error node v6.12.2
45686 error npm  v3.10.10
45687 error path /usr/lib/node_modules/.staging/sprintf-b2430ad9
45688 error code ENOENT
45689 error errno -2
45690 error syscall rename
45691 error enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/sprintf-b2430ad9' -> '/usr/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/node_modules/ipv6/node_modules/sprintf'
45692 error enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/sprintf-b2430ad9' -> '/usr/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/node_modules/ipv6/node_modules/sprintf'
45692 error enoent This is most likely not a problem with npm itself
45692 error enoent and is related to npm not being able to find a file.
45693 verbose exit [ -2, true ]
```

**Comment by sk91** [comment]
Hi,
Please upgrade npm to 4.6.1
sudo npm install -g npm@4.6.1

**Comment by OskHa** [comment]
Thank you, this solved the issues.
