### ISSUE TITLE
login without password

### ISSUE THREAD

**Issue by growield** [luminati-io/luminati-proxy#73]
My LPM has a white IP. When i log in to LPM from one place, anybody can log in to from any place and it won't be asked for a login and password.

**Comment by sk91** [comment]
Hi,
Currently we don't have an option to do it. It is in our todo list.
Meanwhile you can do one of the following:
- whitelist your ip for port 22999 using iptables
- setup apache or nginx as reverse proxy to port 22999 and setup basic auth (you will have to also close
  port 22999 in iptables for remote ips)

**Comment by Hainguyen1210** [comment]
Hi, I am having a problem with this. 
My current setup is a Luminati docker run on a server X, which has basic authentication enabled. I can connect to the Luminati admin page and log in from my computer, however, I cannot add proxy or modify rules, etc. I can see in nginx access log, there is 401 error code. 
Please tell me what I've missed in setting up Luminati.
Many thanks.
