### ISSUE TITLE
Error when Race is set >1 - ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by thisjustin** [luminati-io/luminati-proxy#74]
Using V1.74.626 on ubuntu 16.04 or OSX, using round robin on data center ips. If I set the new `race requests` option to anything greater than 1 I get `ERR_SSL_PROTOCOL_ERROR` whenever I try to make a connection. I've isolated it down to this single setting (although maybe it is conflicting in combination with another setting?)

**Comment by sk91** [comment]
Hi,
Please share which client are you using to connect via lpm.
In case of a default OSX curl, it has a bug that it disables SNI (special ssl extension required to sniff https traffic) https://github.com/curl/curl/issues/1533

Try using a different client for this.

**Comment by sk91** [comment]
I used the following node.js code to test that it actually works:
`var req = require('request');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
req({proxy: 'http://127.0.0.1:24000', url: 'https://lumtest.com/myip.json'}, function(err, res){
  
	if (err)
	    return console.log(err);
	console.log(res.body);
})`
