### ISSUE TITLE
Turning on request logging simply doesn't work

### ISSUE THREAD

**Issue by thisjustin** [luminati-io/luminati-proxy#75]
On OSX using version 1.74.978 (it was present in at least the previous version as well, at some time in the last 3-4 versions it worked). With a round-robin pool using datacenter IPs if I turn on "Log request history" the proxy stops working and refuses to make connections (proxy was previously working - this is the only setting changed). See also my issue with trying to turn on SSL request inspection - without either of these options working it's very hard to debug anything about why requests are failing.

Testing the proxy via the built in tester always shows it working which just isn't accurate at all vs actual usage (I suspect there's some sort of special bypassing going on for test endpoint).

**Comment by sk91** [comment]
Hi,
If you having trouble enabling logging you can do one of the following:
1. After you select the logging settings, restart the luminati process manually
2. run luminati with  --log debug flag or --log info according to your needs
