### ISSUE TITLE
Allow installs of particular versions of the proxy manager

### ISSUE THREAD

**Issue by thisjustin** [luminati-io/luminati-proxy#78]
After a bad build was released that broke the ability to do much of anything at all (see #76 and #77) it's clear that there should be a way to install a particular version of the proxy manager so that if a bad build is released in the future there is a way to revert.

**Comment by sk91** [comment]
Hi,
When installing luminati-proxy via npm (the default way if you are not installing exe on windows) there is a very simple way to switch between versions.
Just peek a release version from https://github.com/luminati-io/luminati-proxy/releases
and run: sudo npm install -g @luminati-io/luminati-proxy@VERSION
