### ISSUE TITLE
Unable to install newer versions.

### ISSUE THREAD

**Issue by dynalz** [luminati-io/luminati-proxy#83]
I'm unable to install newer versions (tested from version 1.75.912 and up). 
Installing 1.70.851 goes fine without any issues. 

# ERROR LOG:
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@luminati-io/luminati-proxy/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-103-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@luminati-io/luminati-proxy" "--unsafe-perm"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/.staging/sprintf-b2430ad9
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/sprintf-b2430ad9' -> '/usr/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/node_modules/ipv6/node_modules/sprintf'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/sprintf-b2430ad9' -> '/usr/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/node_modules/ipv6/node_modules/sprintf'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by assafza** [comment]
Hello dynlaz,

Can you elaborate how you are trying to install newest version?
I would recommend using the BASH script command for linux/mac see here: http://luminati.io/lpm OR use it directly on terminal: curl -L https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh | bash

**Comment by dynalz** [comment]
Simply as:
sudo npm install -g @luminati-io/luminati-proxy --unsafe-perm

I never used curl but will give it a try

**Comment by sk91** [comment]
This happens because of old npm versions. For lpm we recommend using 4.6.1

To upgrade, please run `npm install -g npm@4.6.1`
