### ISSUE TITLE
Proxy manager publicly accessible without luminati login credential?

### ISSUE THREAD

**Issue by webtrend** [luminati-io/luminati-proxy#84]
I am currently running it on Ubuntu server. To access the web UI, I go to <server_ip_address>:22999. I can then login to my luminati account and manage the proxy on my server.

However, when I am logged in, anyone, anywhere can fully access the web UI by typing the IP address and port number in their browser. They have full access to the proxy manager without requiring any credentials. I checked it myself.

I thought that only browser with an active session has access to the proxy manager after logging but it looks like anyone can access it from another browser on another device with a different IP address. Isn't this a security risk? Perhaps, I am misunderstanding the goal here. Can someone elaborate?

**Comment by assafza** [comment]
Hello,

if you run the proxy manager on a server you will need to white list the access to this machine to avoid mis-use of your proxies by unwanted sources.
In addition, we are working on a user management feature which will help securing the service.
http://luminati.io/faq#proxy-security
