### ISSUE TITLE
Where to set the mode parameter in the json?

### ISSUE THREAD

**Issue by igoratencompass** [luminati-io/luminati-proxy#85]
Hi,

It is not clear where do we need to setup the `mode` parameter in the `json` config file nor I can find any reference to its values in the documentation.

Apart from that, a complete example of the `json` config file structure is also missing which makes it difficult to know which parameter belongs to which section (or even what are the possible sections at all) without looking at the source code.

**Comment by JannikZed** [comment]
Yep, would like to ask for the same thing. Would Kindly like to ask for a .luminati.json example as we want the proxy to quietly run in the background with settings written cleanly in the config file.

**Comment by igoratencompass** [comment]
Any update on this please?

**Comment by sk91** [comment]
Hi,

> It is not clear where do we need to setup the mode parameter in the json config file

What do you mean by "mode" parameter? We don't have it in our json. What do you expect it to control?

> Would Kindly like to ask for a .luminati.json example as we want the proxy to quietly run in the
> background with settings written cleanly in the config file.

There are just too many options to do a meaningful example. 

For a background process you can run "luminati -d"

To configure, open ui at 127.0.0.1:22999
Than you will have your config file in ~/.luminati.json

If you need help with a specific configuration, you can ask your success manager (you can find it in your dashboard)

**Comment by igoratencompass** [comment]
Meaning what is the counterpart of the command line `--mode` parameter in the `.luminati.json` file? Same for all the command line parameters given here https://github.com/luminati-io/luminati-proxy#complete-list-of-command-line-options

**Comment by sk91** [comment]
Hi,

>  the counterpart of the command line --mode parameter 
Actually this parameter was deprecated for some time. So our ui will probably not play well with it.
But the api should still work as expected.

Here is a config example:
```
{
  "_defaults": {
    "customer": "test",
    "password": "xxxx",
    "mode": "guest"
  },
  "proxies": [
    {
      "ips": [
      ],
      "keep_alive": 45,
      "last_preset_applied": "sequential",
      "max_requests": 0,
      "pool_size": 1,
      "port": 24000,
      "session_duration": 0,
      "vips": [
      ],
      "whitelist_ips": [
      ],
      "zone": "residential"
    }
  ]
}
```
basically most global cmd options can be set in the _defaults section.

**Comment by igoratencompass** [comment]
Ok if `mode` is deprecated, which is not mentioned in the docs by the way, then what parameter are we suppose to use to remove the admin permissions from the ui?

**Comment by sk91** [comment]
No other way.

Use it. It will not allow making root api calls. But some ui options night be broken in the result
We are working on fixing it
