### ISSUE TITLE
Add static ip in chrome browser 

### ISSUE THREAD

**Issue by Debanjan123** [luminati-io/luminati-proxy#89]
First time i am using luminati.I don't know whether this question is relevant or not.
Actually i am creating chrome extension. I want to change my ip for chrome browse.

**Comment by sk91** [comment]
Hi,

> Actually i am creating chrome extension

First of all you might be interested in our extensions https://chrome.google.com/webstore/detail/luminati/efohiadmkaogdhibjbmeppjpebenaool

To use proxy in your extension you should use the proxy api

https://developer.chrome.com/extensions/proxy

You can read on how to use our api in your dashboard

https://luminati.io/cp/api_example

and in faqs

https://luminati.io/faq

For any specific questions please contact your success manager. (you can find him in your dashboard)
