### ISSUE TITLE
Setting "URL regex for bypassing" deletes all settings

### ISSUE THREAD

**Issue by JannikZed** [luminati-io/luminati-proxy#91]
I'm trying to set a bypassing URL in the General settings page. Alle the time entering values in there I see on the command line: `WARN: 22999 API error: PUT /api/proxies/24000 No proxy at port 24000` and the newly created proxy is gone again .. 

Operating System: MacOS 
Proxy Version: 1.91.108

**Comment by smhall05** [comment]
If you copy and paste the values you want in, instead of manually entering in the UI, I found that to work for me. I was seeing the same thing.

**Comment by fudali** [comment]
Hi! Can you provide us with a bit more info on how to reproduce your issue? I just tried to update `URL regex for bypassing` under `General` tab and it works fine for me. You can also use 'Report a bug` form from the top navigation bar so we can see your logs and debug info

**Comment by JannikZed** [comment]
Did you input a URL regex? I have the feeling, that the moment I'm using brackets, the proxy config just gets deleted. I tested it right now with "(google.de)" and it broke immediately.

**Comment by smhall05** [comment]
When it broke for me I was using parathesis like this (\.jpg$).

**Comment by fudali** [comment]
Thanks for spotting it! It's fixed, pleased upgrade to the newest version
