### ISSUE TITLE
High CPU usage in Google Cloud

### ISSUE THREAD

**Issue by wiliam-paradox** [luminati-io/luminati-proxy#94]
Since I updated the proxy to the 1.93.X version, the usage of the CPU increased gradually until the process restarted (I have a daemon on the proxy).

The machine I'm using for the proxy has 2 cores, one is exclusivelly for Node and the other one for the machine system process. The os is Debian 9. It only has the proxy installed.

![machine usage](https://i.imgur.com/vPxs7UA.png)

**Comment by assafza** [comment]
Hello,
This is Assaf from Lumianti. sorryfor getting back late to this ticket.
Does this issue still relevant on newest version? we made some adjustments lately which might solve this issue.
Can you report back to us after updating to latest version?

**Comment by assafza** [comment]
We have fixed the issue. please update to the latest version.
