### ISSUE TITLE
luminati-proxy-latest-setup.sh downgrades npm version

### ISSUE THREAD

**Issue by RomanIsko** [luminati-io/luminati-proxy#96]
luminati-proxy-latest-setup.sh installs override the latest NPM version with older one (4.6.1)

**Environment:**
Ubuntu 16.04
Node.js 9.11.1
npm version 6.0.0

**Steps:**
1. Node.js LTS is installed
2. upgrade _npm_ package `npm -g install npm` (curretnly the latest npm has version 6.0.0)
3. install  _Luminati Proxy Manager_ by running sh script `wget -qO- https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh | bash`
4. check installation logs

**Actual result:**
....
updating npm to 4.6.1
....

**Expected result:**
installation script should not downgrade npm version

**Comment by romankoblov** [comment]
Fixed in 1.95.360, thanks you for report.
